import type { Metadata } from "next";
import { Barlow } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/common/Navbar";

const barlow = Barlow({
  subsets: ["latin"],
  weight: ["400", "600"], // regular, semibold
  style: ["normal"],
  variable: "--font-barlow",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${barlow.variable}`}>
      <body>
        <Navbar />
        <div className="font-sans grid grid-rows-[20px_1fr_20px] items-center justify-items-center min-h-screen pb-20 gap-16 sm:p-20">
          <main className="flex flex-col gap-[32px] row-start-2 items-center sm:items-start w-full">
            <div className="max-w-7xl mx-auto px-2 lg:px-0 w-full">{children}</div>
          </main>
        </div>
        <footer className="row-start-3 flex gap-[24px] flex-wrap items-center justify-center">
          email: dmytro.deinershtein@gmail.com
        </footer>
      </body>
    </html>
  );
}
